server:
  port: 8088

endpoints:
  shutdown:
    sensitive: false
    enabled: true

flyway:
  baselineOnMigrate: true

spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost/user_test_db
    username: SA
    password: 
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true

core-service:
  host: localhost
  port: 8081
  contextPath: 

document-service:
  host: localhost
  port: 8083
  contextPath: 

front-end-service:
  host: localhost
  port: 8080
  contextPath: 

user-service:
  host: localhost
  port: 8082
  contextPath:
  dataSourceConfiguration:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/USER_TEST_DB
    username: SA
    password:  
     
